services:
  - type: web
    name: the-commonplace
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: IGDB_CLIENT_ID
        sync: false
      - key: IGDB_CLIENT_SECRET
        sync: false
      - key: FANART_TV_API_KEY
        sync: false
      - key: LASTFM_API_KEY
        sync: false
